version: '3.8'

networks:
  inception:
    driver: bridge

volumes:
  wordpress:
  website:
  mariadb:
  
services:
  nginx:
    container_name: nginx
    ports:
      - "443:443"
    depends-on: wordpress


  wordpress:
    container_name: wordpress
    depends-on: mariadb
    restart_policy:
      condition: on-failure

  mariadb:
    container_name: mariadb
    restart_policy:
      condition: on-failure

  redis:

  adminer:

