networks:
  inception:
    driver: bridge

volumes:
  wordpress:
  website:
  mariadb:
  
services:
  nginx:
    image: nginx
    container_name: nginx
    build: requirements/nginx
    ports:
      - "443:443"
    networks:
      - inception
    env_file:
      - .env
    restart: on-failure
 #   depends-on: wordpress


 # wordpress:
  #  container_name: wordpress
   # depends-on: mariadb
   # restart_policy:
   #   condition: on-failure

 # mariadb:
  #  container_name: mariadb
   # restart_policy:
    #  condition: on-failure

    #  redis:

    #  adminer:

